### ISSUE TITLE
Decide on Scope

### ISSUE THREAD

**Issue by drewlearns** [drewlearns/100daysofcode_reminder_app#8]
Scope as I see it currently:
- Remind the user (via email?) daily at a certain time if they haven't commented
- work with twitter API to make a post - auto prepends #100daysofcode and the day that you are on
- Limits characters per twitter 
- Maybe work with linkedin?
- continue discussion for further scope. 

We want to narrow the scope before coding to determine what platforms and technologies to use.

**Comment by Hyperi0nGit** [comment]
IMO We should just go with Twitter to keep it simple.
I like the idea of email reminders except that email is easy to miss. 
Would it be complex to have mobile notifications instead or as well as email?
Needs to be able to turn on and off 
Does it need a schedule function so posts can be scheduled at a particular time?
Does it need to integrate with Grammarly or a spell checker API?
Would need to allow for the upload of screenshots or video?

**Comment by renners7777** [comment]
How about having a motivational quote each day - on the website and emailed to the individual along with the reminder? When I tried completing 100daysofcode, I got to about day 60 but had long periods of time (months) when I didn't put anything down so having something motivational would help I think.

**Comment by Hyperi0nGit** [comment]
That's an awesome idea.

**Comment by drewlearns** [comment]
I like the mot. quote idea, hate email. Let's do it

**Comment by drewlearns** [comment]
https://zenquotes.io/

**Comment by drewlearns** [comment]
https://api-ninjas.com/api/quotes

**Comment by renners7777** [comment]
https://rapidapi.com/collection/quote-generator-apis

**Comment by renners7777** [comment]
I have created a separate issue for the "motivational quote" API

**Comment by Hyperi0nGit** [comment]
> I like the mot. quote idea, hate email. Let's do it

Oh man I get sooo many e-mails LOL there is so much I want to read but don't have time too and have to unsubscribe binge regularly

**Comment by drewlearns** [comment]
testing webhooks

**Comment by Hyperi0nGit** [comment]
I have a couple of items regarding the scope to discuss at the next meeting: 

1. the potential idea of the app's integration with Google Calendar? 

To give some context -  The user creates a daily repeating appointment or reminder - or the app creates one on Google Calendar for their 100 Days Of Code and the app picks up the scheduled appointment and then prompts the user along with motivational quotes via whatever method we will use to keep the user engaged. (lock screen on mobile, e-mail, text, whatever we decide).

The advantage of the above is that it would reduce complexity in the app because all the scheduling could be done in Google Calendar. This idea means if the person chooses to change the time On their calendar, it will auto-adjust the reminder from the app and when the person looks at their appointments and reminders on their calendar it will be right there in front of them in their agenda.


2. The idea of the app being a wallpaper reminder app?

The advantage is that motivational quotes, reminders etc could appear as the user's wallpaper on their device.
The disadvantage is that it limits the app to the device wallpaper, so there is a loss of some flexibility if the user wants to change their wallpaper.
